language: java
jdk:
    - oraclejdk8
services:
    - mysql
deploy:
    provider: heroku
    api-key:
        secure: $HEROKU_API_KEY
    app: iv1201-recruit-server
    on:
        repo: Moa-DB/recruitserver
env:
    - SPRING_PROFILES_ACTIVE=travis
before_install:
    - chmod a+x mvnw
    - mysql -e 'CREATE DATABASE IF NOT EXISTS recruit;'
    - export MIGRATE=TRUE
    
