spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recruit?useSSL=false
    username: root
    password: password
    platform: mysql
  jpa:
    hibernate:
          ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


---
spring:
  profiles: heroku
  server:
      port: ${PORT}
  datasource:
    url: ${CLEARDB_DATABASE_URL}&useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: ${CLEARDB_USER}
    password: ${CLEARDB_PASSWORD}
    platform: mysql
  jpa:
    hibernate:
          ddl-auto: update
